/* This file only contains comments, to provide documentation
generated by Doxygen. No need to include this file in the distribution */

/**

\page libMidi-Me_page libMidi-Me

\section intro_sec Introduction
The libMidi-Me library can be used to access all functionality of Midi-Me except for the visual editing,
which is implemented under a different licence. You also have to link with this library to develop
Midi-Me plugins.


*/
