/* This file only contains comments, to provide documentation
generated by Doxygen. No need to include this file as source code */

/**

\mainpage Midi-Me

\section intro_sec Introduction
Midi-Me is an application that converts input signals to midi-out signals,
using a graphical flow-editor where you can connect outputs to inputs very easily.

Midi-Me only uses cross-platform libraries in its implementation, making ports to other platforms
very easy. It also uses a plugin system so external developers can provide support for new
input devices and value processors. Note that plugins can be platform-specific if they need to be.

Midi-Me consists of a library and an application. The application is distributed under the GPL license
because it uses the open-source version of Qt. You only need the application to visually edit processor chains.

The library (libMidi-Me) is distributed under the LGPL licence. The only external library used there
is RtMidi, which allows this. You can use the library in your own software very easily to provide the processing
functionality of Midi-Me and to load/save chains from/to XML.

The PluginSystem and XmlParser libraries used in Midi-Me are licenced under LGPL too, so you can use them in your
own software if you want to.

*/
